Update patch set 1
Patch Set 1: Code-Review-1

(1 comment)

On system: Fips gets disabled.

In spec tests: init_spec expects bootmode => normal, but it is now 'nil' due to the bug in augeasproviders and need to be accounted for.

In acceptance tests:
       	Error: Failed to parse template pam/etc/pam.d/auth.erb:
       	  Filepath: /usr/share/ruby/vendor_ruby/puppet/util/package.rb
       	  Line: 4
       	  Detail: undefined method `scan' for nil:NilClass
       	 at /etc/puppet/modules/pam/manifests/auth.pp:58

Patch-set: 1
Reviewer: nmarkowski@keywcorp.com <1005194@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=-1